config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  root 'conversations#index'

  mount Sidekiq::Web => '/sidekiq'

  resources :users, only: [:index]
  resources :personal_messages, only: [:new, :create, :show]
  resources :conversations, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: { scope: :receiver }

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true

  after_create_commit do
    conversation.touch
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy

  def online?
    Redis.new.get("user_#{self.id}_online").present?
  end

  def name
    email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
  end

  def show
    @personal_message = PersonalMessage.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/personal_messages_controller.rb
class PersonalMessagesController < ApplicationController
  before_action :find_conversation!

  def new
    redirect_to conversation_path(@conversation) and return if @conversation
    @personal_message = current_user.personal_messages.build
  end

  def create
    @conversation ||= Conversation.create(author_id: current_user.id, receiver_id: @receiver.id)
    @personal_message = current_user.personal_messages.build(personal_message_params)
    @personal_message.conversation_id = @conversation.id

    respond_to do |format|
      if @personal_message.save!
        ActionCable.server.broadcast('room_channel', body: @personal_message.body, sender: current_user.name)
        ActionCable.server.broadcast("notifier_#{@conversation.with(current_user).id}_channel",
                                     notification: render_notification(@personal_message),
                                     conversation_id: @personal_message.conversation.id)
        format.js
      end
    end
  end

  def show
  end

  private

  def personal_message_params
    params.require(:personal_message).permit(:body)
  end

  def find_conversation!
    if params[:receiver_id]
      @receiver = User.find_by(id: params[:receiver_id])
      redirect_to(root_path) and return unless @receiver
      @conversation = Conversation.between(current_user.id, @receiver.id)[0]
    else
      @conversation = Conversation.find_by(id: params[:conversation_id])
      redirect_to(root_path) and return unless @conversation && @conversation.participates?(current_user)
    end
  end

  def render_notification(message)
    NotificationsController.render partial: 'notifications/notification', locals: { message: message }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def online_status(user)
    content_tag :span, user.name,
                id: "user-#{user.id}",
                class: "online_status #{'online' if user.online?}"
  end
end

app/views/conversations/_conversation.html.erb
<div>
  Chatting with <%= conversation.with(current_user).name %>
  <br>
  <em><%= conversation.personal_messages.last.body.truncate(50) %></em>
  <br>
  <%= link_to 'View conversation', conversation_path(conversation) %>
  <hr>
</div>

app/views/conversations/index.html.erb
<h1>Your conversations</h1>

<div id="conversations">
  <%= render @conversations %>
</div>

app/views/conversations/show.html.erb
<h1>Chatting with <%= online_status(@conversation.with(current_user)) %></h1>

<div id="conversation-main">
  <div id="conversation-body">
    <%= render @conversation.personal_messages %>
  </div>

  <div id="new_message"%></div>
  <div id="status"%></div>

  <%= form_with(model: @personal_message, remote: true) do |f| %>
    <%= hidden_field_tag 'conversation_id', @conversation.id %>
    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit 'Send' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div>
        <%= value %>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <p>Signed in as <%= current_user.name %> | <%= link_to 'log out', destroy_user_session_path, method: :delete %></p>
      <li><%= link_to 'Users', users_path %></li>
    <% end %>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/notifications/_notification.html.erb
<div id="notification">
  <div class="close">Close</div>
  <p>
    <%= message.body %><br>
    from <%= message.user.name %>
  </p>
  <p><%= link_to 'Open convo', conversation_path(message.conversation) %></p>
</div>

app/views/personal_messages/_personal_message.html.erb
<p><strong><%= personal_message.user.name %></strong>:&nbsp&nbsp<%= personal_message.body %>&nbsp&nbsp
at <%= personal_message.created_at %></p>

app/views/personal_messages/new.html.erb
<h1>New message to <%= @receiver.name %></h1>

<%= form_with(model: @personal_message, remote: true) do |f| %>
  <%= hidden_field_tag 'receiver_id', @receiver.id %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit 'Send' %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= user.name %> | <%= link_to 'send a message', new_personal_message_path(receiver_id: user) %>
</li>

app/views/users/index.html.erb
<h1>Users</h1>

<ul><%= render @users %></ul>